image: node:latest

variables:
    mode: "testing"
    databaseString: "mongodb://mongo:27017/cs_grad_data-test"
    port: "8080"
    host: "127.0.0.1"
    npm_config_cache: "$CI_PROJECT_DIR/.npm"
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"


services:
    - mongo:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - cache/Cypress

install_dependencies:
  image: cypress/base:10
  stage: build
  script:
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm install -g start-server-and-test
    - npm install cypress
    - npm run ci