image: node:latest

variables:
    mode: "testing"
    databaseString: "mongodb://mongo:27017/cs_grad_data-test"
    port: "8080"
    host: "127.0.0.1"

services:
    - mongo:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm install -g wait-on
    - npm test & wait-on http://localhost:8080
    - npx cypress run