image: node:latest

variables:
    mode: "testing"
    databaseString: "mongodb://mongo:27017/cs_grad_data-test"
    port: "8080"
    host: "127.0.0.1"

services:
    - mongo:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm install -g start-server-and-test
    - npm install cypress
    - npm run ci