image: node:latest
image: cypress/base:10

variables:
    mode: "testing"
    databaseString: "mongodb://mongo:27017/cs_grad_data-test"
    port: "8080"
    host: "127.0.0.1"
    npm_config_cache: "$CI_PROJECT_DIR/.npm"
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"


before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

services:
    - mongo:latest

stages:
  - build
  - test
  - deploy


cache:
  paths:
    - .npm
    - node_modules/
    - cache/Cypress

install_dependencies:
  stage: build
  script:
    - npm ci
    - npx cypress cache path
    - npx cypress cache list
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm install -g start-server-and-test
    - npm run ci

deployment:
  stage: deploy
  script:
    - ssh root@csgrad.cs.unc.edu "cd .."